#sample yml 
trigger:
  none
pool:
  name: newpool
  demands:
    -agent.name -equals MS-Hosted

stages:
  - stage: complile
    displayName: "complile"
    jobs:
      - job:
        steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'practice'
    command: 'build'
